services:
  science-solver:
    env_file: '.env'
    image: science-solver
    privileged: true # Required for running Apptainer on some systems
    user: "${UID}:${GID}" # User is configured in .env file. If you encounter permission issues, try to remove this line
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './domains:/ws/domains'
      - './results:/ws/results'
      - './science_solver:/ws/science_solver'
      - './main.py:/ws/main.py'
