services:
  nl2plan:
    env_file: '.env'
    image: nl2plan
    privileged: true # Required for running Apptainer on some systems
    user: "${UID}:${GID}" # User is configured in .env file. If you encounter permission issues, try to remove this line
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './domains:/ws/domains'
      - './results:/ws/results'
      - './pddl0-results:/ws/pddl0-results'
      - './NL2Plan:/ws/NL2Plan'
      - './PDDL0:/ws/PDDL0'
      - './main.py:/ws/main.py'